### ISSUE TITLE
Dropdowns are limited to plain text

### ISSUE THREAD

**Issue by michens** [IUeDS/quickcheck#81]
The Math department at IUE uses quick checks, but the experience is unpleasant for students if the options contain formatting in Latex. 

I made a quick Tampermonkey hack to replace the dropdowns with buttons supporting formatting [here](https://gist.github.com/michens/c8a65d75fea95716145cc81f13fe8201).

This changes the experience from ![qc-before](https://github.com/user-attachments/assets/6a4f7163-cdcf-4903-98ac-061bf5673169)
to ![qc-after](https://github.com/user-attachments/assets/145f8547-5d28-4755-b9a0-d82149ee9618).

This is a dirty hack and not a viable, long-term solution, but it is still a clear improvement for this scenario. It seems like it should be straightforward to update [dropdowns](https://github.com/IUeDS/quickcheck/blob/f7752f2f587b456ba88f1f50cff79b0bc8ef1efe/resources/assets/src/app/components/assessment/dropdowns/dropdowns.component.html) to use something like [CoreUI dropdown](https://coreui.io/angular/docs/components/dropdown/) / [Material select](https://material.angular.io/components/select/overview) / [PrimeNG dropdown](https://primeng.org/dropdown) instead of the native select/option elements so that it would support formatting.

Would a PR for this get considered?

**Comment by mattmallon** [comment]
Hi Michael,

I appreciate all of the work and depth you put into this feature request! The use case certainly makes sense to me. I think the biggest hurdle here is going to be accessibility. Federal legal requirements for accessibility in online higher education continue to be more and more stringent, and IU is making it a top priority in Quick Check and other applications to remain compliant with the law. I'll run this idea by the accessibility experts at ATAC the next time we meet with them and see what they think. I'm a little concerned that the documentation for some of these libraries either don't include any mention of accessibility or mention explicitly that the standard select html element is highly preferable for cross-platform accessibility. Also, because mathjax (the library we are using for converting LaTeX into readable formatting) contains interactive content that allows screenreader users to have the math formatting read aloud to them in an accessible fashion, it seems that it would likely be inaccessible and against the html5 spec to nest interactive content inside a button. I'll ask the accessibility experts though to see what they think and if they have any suggestions for alternatives.

For the time being, I would recommend that you do not copy and paste equation editor LaTeX into the select options for dropdown questions, as we are using the mathjax library for conversion and [only plain text is supported in the HTML5 standard](https://github.com/mathjax/MathJax/issues/1476). It almost certainly would not be accessible content. 

I know it's not as elegant a solution and may not look as clean with the lengthy equation examples you have given, but an accessible workaround for the moment would be to format the question as a multiple choice question with blanks listed in the question text and multiple options delineated in the multiple choice options, like so (I'm making up some random answer options here for the sake of demonstration!):

Question:
First, prove that [answer option 1]. Assume that [answer option 2]. Prove that it follows that [answer option 3].

Options: 

A) Option 1: 3a + b = 42; Option 2: 6b + 47 = 2a; Option 3: 2a + 5 = 59
B) Option 1: 6b + 2 = 5a; Option 2: 6b + 47 = 2a; Option 3: 97 - 4a = 3b
C) etc.
D) etc.

Hopefully that makes sense. I'm not an expert in these matters so I'm sure that the accessibility center would have some additional ideas if you'd like to reach out to them for a consultation! 

Thank you!

**Comment by michens** [comment]
Thank you for the response. Accessibility is important and any changes here could not be allowed to make the page less accessible for other scenarios. This is unfortunately a real quick check that has existed for years that fails to be accessible to anyone, regardless of screen reader usage. 

While it would be ideal to have rich dropdown support for this scenario, it may not be possible (or worth the work required) to have full-featured support for Latex. As such, the alternative solution proposed may be the correct path forward, though it looks cumbersome for this particular question. I see that there is something that looks like a [drag-and-drop](https://github.com/IUeDS/custom-activities/tree/master/drag-and-drop) activity in another repo, though I'm not entirely sure what it is. Would this also be a possibility for updating this type of quick check for future classes?

**Comment by mattmallon** [comment]
The drag and drop question type is currently in an alpha piloting stage. The functionality is there, but once again, we are consulting with the accessibility center to make that question type accessible, and it may be several months before we release the feature to all users. I can ask them as well about the possibility of including mathjax for the draggables (either as  alt text to a draggable image or as draggable text). Functionality-wise, I think it would be suitable to do what you're seeking to do.

**Comment by mattmallon** [comment]
Hi Michael,

I wanted to follow up and let you know that I did reach out to ATAC to ask about the possibility of including the functionality you mentioned in an accessible manner. Unfortunately, their response was what I expected, that it would be inaccessible to nest interactive content by including interactive mathjax content inside of another interactive element like a button (or draggable option, if we went the drag and drop route). Their recommendation for accessibility was in line with what I recommended, to offer a multiple choice question with different permutations of possible answers within each answer option.

Thanks,
Matt
